apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-b7a6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-b7a6
    app.kubernetes.io/part-of: test-rhtap-13-app
  name: devfile-sample-code-with-quarkus-b7a6
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-b7a6
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-b7a6
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-13-tenant/test-rhtap-13-app/devfile-sample-code-with-quarkus-b7a6@sha256:7a7c438a6ec80560a393a9a38d10ce9d2f2eec89d12fbfec5797102ed1424bc2
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
